sudo: required
dist: trusty
group: edge
language: node_js
addons:
  chrome: stable

branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '8'
before_install:
  - mkdir temp
before_script:
  - npm prune
script:
  - npm run build
  - npm run cover
  - npm run check-coverage
after_success:
  - npm run report-coverage
  - npm run semantic-release