sudo: required
dist: trusty
language: node_js
addons:
  chrome: stable
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '8'
before_install:  
  - npm i -g npm@^5.0.0
  - mkdir temp
before_script:
  - npm prune
script:
  - npm run build
  - npm run cover
  - npm run check-coverage
after_success:
  - npm run report-coverage
  - npm run semantic-release