version: '3'

services:
  nginx:
    container_name: hfc-nginx-lb
    build: ./nginx
    links:
      - "node1"
      - "node2"
    ports:
      - "8000:80"
    depends_on:
      - node1
      - node2
  
  node1:
    container_name: hfc1
    image: vvc/hfc
    build: .
    expose:
      - "8000"
    privileged: true
    environment:
      - DEBUG=*

  node2:
    container_name: hfc2
    image: vvc/hfc
    build: .
    expose:
      - "8000"
    privileged: true
    environment:
      - DEBUG=*
